services:
  app:
    build: .
    container_name: rastros_musical_app
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DATABASE_PATH=/app/data/processed/rastros.duckdb
      - PYTHONPATH=/app
    stdin_open: true
    tty: true

volumes:
  duckdb_data: