"""Genre origin data curated from Wikipedia and musicological sources."""

GENRE_ORIGINS = {
    "samba": {
        "country_code": "BR",
        "country_name": "Brazil",
        "region": "Latam",
        "year_start": 1860,
        "description": "Emerged in Bahia in the late 19th century.",
    },
    "bossa nova": {
        "country_code": "BR",
        "country_name": "Brazil",
        "region": "Latam",
        "year_start": 1958,
        "description": "Emerged in Rio de Janeiro with João Gilberto.",
    },
    "tango": {
        "country_code": "AR",
        "country_name": "Argentina",
        "region": "Latam",
        "year_start": 1880,
        "description": "Emerged in Buenos Aires and Montevideo.",
    },
    "mariachi": {
        "country_code": "MX",
        "country_name": "Mexico",
        "region": "Latam",
        "year_start": 1830,
        "description": "Originated in the state of Jalisco. ",
    },
    "cumbia": {
        "country_code": "CO",
        "country_name": "Colombia",
        "region": "Latam",
        "year_start": 1820,
        "description": "Emerged from Caribbean coast influences.",
    },
    "vallenato": {
        "country_code": "CO",
        "country_name": "Colombia",
        "region": "Latam",
        "year_start": 1940,
        "description": "Originated in the Valledupar region.",
    },
    "merengue": {
        "country_code": "DO",
        "country_name": "Dominican Republic",
        "region": "Latam",
        "year_start": 1844,
        "description": "Emerged in the Dominican Republic.",
    },
    "bachata": {
        "country_code": "DO",
        "country_name": "Dominican Republic",
        "region": "Latam",
        "year_start": 1960,
        "description": "Emerged from rural communities.",
    },
    "salsa": {
        "country_code": "CU",
        "country_name": "Cuba",
        "region": "Latam",
        "year_start": 1940,
        "description": "Emerged from Cuban son and Caribbean rhythms.",
    },
    "reggaeton": {
        "country_code": "PR",
        "country_name": "Puerto Rico",
        "region": "Latam",
        "year_start": 1980,
        "description": "Emerged in Puerto Rico from reggae and hip-hop.",
    },
    "sertanejo": {
        "country_code": "BR",
        "country_name": "Brazil",
        "region": "Latam",
        "year_start": 1929,
        "description": "Originated in rural Brazil as música caipira.",
    },
    "mpb": {
        "country_code": "BR",
        "country_name": "Brazil",
        "region": "Latam",
        "year_start": 1960,
        "description": "Emerged after Bossa Nova.",
    },
    "k-pop": {
        "country_code": "KR",
        "country_name": "South Korea",
        "region": "Asia",
        "year_start": 1992,
        "description": "Started with Seo Taiji and Boys in 1992.",
    },
    "j-pop": {
        "country_code": "JP",
        "country_name": "Japan",
        "region": "Asia",
        "year_start": 1987,
        "description": "Emerged in the 1990s as Japanese pop identity.",
    },
    "bollywood": {
        "country_code": "IN",
        "country_name": "India",
        "region": "Asia",
        "year_start": 1931,
        "description": "Started with India's first sound film.",
    },
    "mandopop": {
        "country_code": "CN",
        "country_name": "China",
        "region": "Asia",
        "year_start": 1920,
        "description": "Originated in Shanghai in the 1920s.",
    },
    "cantopop": {
        "country_code": "HK",
        "country_name": "Hong Kong",
        "region": "Asia",
        "year_start": 1970,
        "description": "Emerged in Hong Kong with Sam Hui and Roman Tam.",
    },
    "dangdut": {
        "country_code": "ID",
        "country_name": "Indonesia",
        "region": "Asia",
        "year_start": 1950,
        "description": "Emerged from Malay, Indian, and Arabic influences.",
    },
    "qawwali": {
        "country_code": "PK",
        "country_name": "Pakistan",
        "region": "Asia",
        "year_start": 1200,
        "description": "Sufi devotional music with origins in the 13th century.",
    },
    "enka": {
        "country_code": "JP",
        "country_name": "Japan",
        "region": "Asia",
        "year_start": 1950,
        "description": "Post-war Japanese popular ballad style.",
    },
}
