name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync --frozen --dev

      - name: Run Ruff (Linter & Formatter check)
        run: |
          uv run ruff check .
          uv run ruff format --check .

      - name: Run Tests with Coverage
        id: pytest
        run: |
          uv run pytest --cov=app --cov-report=term-missing > coverage.txt
          cat coverage.txt
          PERCENTAGE=$(grep 'TOTAL' coverage.txt | awk '{print $NF}' | sed 's/%//')
          echo "COVERAGE_PERCENTAGE=$PERCENTAGE" >> $GITHUB_ENV

      - name: Generate Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 66c52db472148abeda19137803004a81
          filename: coverage.json
          label: Coverage
          message: ${{ env.COVERAGE_PERCENTAGE }}%
          color: green
        if: github.ref == 'refs/heads/main'